// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Suave.IIS")>]
[<assembly: AssemblyProductAttribute("Suave.IIS")>]
[<assembly: AssemblyDescriptionAttribute("")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Suave.IIS"
    let [<Literal>] AssemblyProduct = "Suave.IIS"
    let [<Literal>] AssemblyDescription = ""
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
