// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Suave.IIS")>]
[<assembly: AssemblyProductAttribute("Suave.IIS")>]
[<assembly: AssemblyDescriptionAttribute("Set of helper functions for smooth running Suave web server on Internet Information Services (IIS)")>]
[<assembly: AssemblyVersionAttribute("2.2.0")>]
[<assembly: AssemblyFileVersionAttribute("2.2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Suave.IIS"
    let [<Literal>] AssemblyProduct = "Suave.IIS"
    let [<Literal>] AssemblyDescription = "Set of helper functions for smooth running Suave web server on Internet Information Services (IIS)"
    let [<Literal>] AssemblyVersion = "2.2.0"
    let [<Literal>] AssemblyFileVersion = "2.2.0"
